config/routes.rb
BookmarkCentral::Application.routes.draw do
  resources :clouds
  resources :bookmarks
  resources :labels

  match '/labels', :to => 'labels#index'
  match '/bookmarks', :to => 'bookmarks#index'
  match '/clouds', :to => 'clouds#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  has_many :label
end

app/models/cloud.rb
class Cloud < ActiveRecord::Base
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
require 'pry'

class BookmarksController < ApplicationController
  # GET /bookmarks
  # GET /bookmarks.xml
  def index
    binding.pry
    @bookmarks = Bookmark.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.xml
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.xml
  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.xml
  def create
    @bookmark = Bookmark.new(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully created.') }
        format.xml  { render :xml => @bookmark, :status => :created, :location => @bookmark }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.xml
  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.xml
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to(bookmarks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController
  # GET /clouds
  # GET /clouds.json
  def index
    @clouds = Cloud.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clouds }
    end
  end

  # GET /clouds/1
  # GET /clouds/1.json
  def show
    @cloud = Cloud.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cloud }
    end
  end

  # GET /clouds/new
  # GET /clouds/new.json
  def new
    @cloud = Cloud.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cloud }
    end
  end

  # GET /clouds/1/edit
  def edit
    @cloud = Cloud.find(params[:id])
  end

  # POST /clouds
  # POST /clouds.json
  def create
    @cloud = Cloud.new(params[:cloud])

    respond_to do |format|
      if @cloud.save
        format.html { redirect_to @cloud, notice: 'Cloud was successfully created.' }
        format.json { render json: @cloud, status: :created, location: @cloud }
      else
        format.html { render action: "new" }
        format.json { render json: @cloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clouds/1
  # PUT /clouds/1.json
  def update
    @cloud = Cloud.find(params[:id])

    respond_to do |format|
      if @cloud.update_attributes(params[:cloud])
        format.html { redirect_to @cloud, notice: 'Cloud was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clouds/1
  # DELETE /clouds/1.json
  def destroy
    @cloud = Cloud.find(params[:id])
    @cloud.destroy

    respond_to do |format|
      format.html { redirect_to clouds_url }
      format.json { head :ok }
    end
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  # GET /labels
  # GET /labels.xml
  def index
    @labels = Label.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @labels }
    end
  end

  # GET /labels/1
  # GET /labels/1.xml
  def show
    @label = Label.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @label }
    end
  end

  # GET /labels/new
  # GET /labels/new.xml
  def new
    @label = Label.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @label }
    end
  end

  # GET /labels/1/edit
  def edit
    @label = Label.find(params[:id])
  end

  # POST /labels
  # POST /labels.xml
  def create
    @label = Label.new(params[:label])

    respond_to do |format|
      if @label.save
        format.html { redirect_to(@label, :notice => 'Label was successfully created.') }
        format.xml  { render :xml => @label, :status => :created, :location => @label }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @label.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /labels/1
  # PUT /labels/1.xml
  def update
    @label = Label.find(params[:id])

    respond_to do |format|
      if @label.update_attributes(params[:label])
        format.html { redirect_to(@label, :notice => 'Label was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @label.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.xml
  def destroy
    @label = Label.find(params[:id])
    @label.destroy

    respond_to do |format|
      format.html { redirect_to(labels_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
  def labels
    Label.find :all do |label|
      label.title
    end
  end

  def labels_for_bookmark(bookmark)
    Label.find_all_by_bookmarks_id(bookmark.id) do |label|
      label.title
    end
  end
end

app/helpers/clouds_helper.rb
module CloudsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
      <ul>
        <% @bookmark.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :last_visited %>
    <br />
    <%= f.datetime_select :last_visited %>
  </div>
  <div class="field">
    <%= f.label :times_visited %>
    <br />
    <%= f.text_field :times_visited %>
  </div>
  <div class="field">
  <%= select_tag('label', options_from_collection_for_select(Label.all, 'id', 'name')) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>
<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %> 

app/views/bookmarks/index.html.erb
<h1>Listing bookmarks</h1>
<table>
	<tr>
		<th>Title</th>
		<th>Url</th>
		<th>Last visited</th>
		<th>Times visited</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @bookmarks.each do |bookmark| %>
	<tr>
		<td><%= bookmark.title %></td>
		<td><%= bookmark.url %></td>
		<td><%= bookmark.last_visited %></td>
		<td><%= bookmark.times_visited %></td>
		<td><%= link_to 'Show', bookmark %></td>
		<td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
		<td><%= link_to 'Destroy', bookmark, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
	<% end %>
</table>
<br />
<%= link_to 'New Bookmark', new_bookmark_path %> 

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= render 'form' %>

<%= link_to 'Back', bookmarks_path%> 

app/views/bookmarks/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<p>
	<b>Title:</b>
	<%= @bookmark.title %>
</p>
<p>
	<b>Url:</b>
	<%= @bookmark.url %>
</p>
<p>
	<b>Last visited:</b>
	<%= @bookmark.last_visited %>
</p>
<p>
	<b>Times visited:</b>
	<%= @bookmark.times_visited %>
</p>
<p>
	<b>Labels:</b>
	<%= labels_for_bookmark(@bookmark) %>
</p>
<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %> 

app/views/clouds/_form.html.erb
<%= form_for(@cloud) do |f| %>
  <% if @cloud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cloud.errors.count, "error") %> prohibited this cloud from being saved:</h2>

      <ul>
      <% @cloud.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clouds/edit.html.erb
<h1>Editing cloud</h1>

<%= render 'form' %>

<%= link_to 'Show', @cloud %> |
<%= link_to 'Back', clouds_path %>

app/views/clouds/index.html.erb
<h1>Listing clouds</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clouds.each do |cloud| %>
  <tr>
    <td><%= link_to 'Show', cloud %></td>
    <td><%= link_to 'Edit', edit_cloud_path(cloud) %></td>
    <td><%= link_to 'Destroy', cloud, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cloud', new_cloud_path %>

app/views/clouds/new.html.erb
<h1>New cloud</h1>

<%= render 'form' %>

<%= link_to 'Back', clouds_path %>

app/views/clouds/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_cloud_path(@cloud) %> |
<%= link_to 'Back', clouds_path %>

app/views/labels/_form.html.erb
<%= form_for(@label) do |f| %>
<% if @label.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>
	<ul>
		<% @label.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<%= f.label :name %>
	<br />
	<%= f.text_field :name %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

app/views/labels/edit.html.erb
<h1>Editing label</h1>
<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %> 

app/views/labels/index.html.erb
<h1>Listing labels</h1>
<table>
	<tr>
		<th>Name</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @labels.each do |label| %>
	<tr>
		<td><%= label.name %></td>
		<td><%= link_to 'Show', label %></td>
		<td><%= link_to 'Edit', edit_label_path(label) %></td>
		<td><%= link_to 'Destroy', label, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
	<% end %>
</table>
<br />
<%= link_to 'New Label', new_label_path %> 

app/views/labels/new.html.erb
<h1>New label</h1>
<%= render 'form' %>

<%= link_to 'Back', labels_path %> 

app/views/labels/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<p>
	<b>Name:</b>
	<%= @label.name %>
</p>
<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %> 

app/views/layouts/_header.html.erb
<header>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "Label", labels_path %>
			</li>
			<li>
				<%= link_to "Bookmark", bookmarks_path %>
			</li>
			<li>
				<%= link_to "Cloud", clouds_path %>
			</li>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BookmarkCentral</title>
		<%= stylesheet_link_tag :all %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
	</body>
</html>